name: Continuous Integration

on:
  pull_request:
    paths-ignore:
      - '**/README.md'
  push:
    branches:
      - 'release/**'
      - 'hotfix/**'
      - develop
      - master

jobs:
  part-1:
    name: Test Set Variable
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.branch.outputs.branch_name }}
    steps:
      - name: Set
        id: branch
        run: echo "branch_name=this-is-a-test" >> $GITHUB_OUTPUT

      - name: Fail if not set
        if: ${{ !steps.branch.outputs.branch_name }}
        run: exit 1
  
  part-2:
    name: Test Access Varible
    runs-on: ubuntu-latest
    needs:
      - part-1
    env:
      VAR: ${{ needs.part-1.outputs.branch_name }}
    steps:
      - name: Access direct
        run: echo "Access direct ${{ needs.create-release-tag.outputs.branch_name }}"

      - name: Access env
        run: echo "Access env $VAR"
