name: Update Korpyhe Version
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Korpyhe Version'
        required: true

jobs:
  update-koryphe-version:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Dmaven.wagon.http.retryHandler.count=3 -Dmaven.wagon.httpconnectionManager.ttlSeconds=25
      VERSION_UPDATE_BRANCH: update-koryphe-version-${{ github.event.inputs.version }}

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Get branch name
      run: echo "SOURCE_BRANCH=$(git branch --show-current)" >> $GITHUB_ENV

    - name: Set up Github credentials
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com

    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Update Korpyhe Version
      run: ./cd/updateKorypheVersion.sh ${{ github.event.inputs.version }}

    - name: Submit PR
      if: ${{ success() }}
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ${{ env.VERSION_UPDATE_BRANCH }}
        destination_branch: ${{ env.SOURCE_BRANCH }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
